// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zwnmwhzoynstrmxqituh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp3bm13aHpveW5zdHJteHFpdHVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ2NDc5NjUsImV4cCI6MjA1MDIyMzk2NX0.xR0pxgu3FgWpRSbgrmd8aQIHD-dZtYEQkQJSBMZj6hY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);